apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repo }}:{{ .Values.image.version }}
        env:
        - name: ALLOW_SIGNUP
          value: "{{ .Values.environment.allowSignup }}"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "{{ .Values.environment.timezone }}"
        - name: MAX_WORKERS
          value: "1"
        - name: WEB_CONCURRENCY
          value: "1"
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}